version: "3.9"

services:
  fraud:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app/db:/app/db
    environment:
      - PYTHONPATH=/code
    command: uvicorn main:app --host 0.0.0.0 --port 8000